import { readFile, writeFile, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const directory = new URL('../book/parts/', import.meta.url);
const target = new URL('../site/index.html', import.meta.url);

export async function buildBook(check = false) {
  const parts = (await readdir(directory)).filter(name => name.endsWith('.html')).sort();
  const fragments = await Promise.all(parts.map(name => readFile(new URL(name, directory), 'utf8')));
  const content = '<!-- Generated by scripts/build-book.mjs. Edit book/parts/*.html. -->\n' + fragments.join('');
  if (check) {
    if (await readFile(target, 'utf8') !== content) throw new Error('Book is stale. Run npm run build after editing book/parts.');
    console.log(`Book assembly current: ${parts.length} parts.`);
  } else {
    await writeFile(target, content);
    console.log(`Assembled ${parts.length} parts into ${fileURLToPath(target)}.`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await buildBook(process.argv.includes('--check'));
